# Generated by Django 4.1.7 on 2023-03-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("create_hierarchy", "0002_alter_employee_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="create_hierarchy.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="create_hierarchy.employee",
            ),
        ),
    ]
