# Generated by Django 4.1.7 on 2023-03-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("create_hierarchy", "0003_employee_parent_alter_employee_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="parent",
        ),
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="create_hierarchy.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("0", "Seo"),
                    ("lead", "Lead"),
                    ("senior", "Senior"),
                    ("middle", "Middle"),
                    ("junior", "Junior"),
                    ("trainee", "Trainee"),
                ],
                max_length=255,
            ),
        ),
    ]
