# Generated by Django 4.1.7 on 2023-03-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "create_hierarchy",
            "0004_remove_employee_parent_alter_employee_manager_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("0", "seo"),
                    ("lead", "Lead"),
                    ("senior", "Senior"),
                    ("middle", "Middle"),
                    ("junior", "Junior"),
                    ("trainee", "Trainee"),
                ],
                max_length=255,
            ),
        ),
    ]
